# Generated by Django 3.0.5 on 2020-05-17 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Tire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=0)),
                ('profile', models.FloatField(default=0)),
                ('diameter', models.CharField(blank=True, max_length=20)),
                ('seoson', models.CharField(choices=[('Летние', 'Summer'), ('Зимние', 'Winter'), ('Всесезонные', 'Mixed')], default='Summer', max_length=11)),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='Disc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.FloatField(default=0)),
                ('fasteners_quantity', models.IntegerField()),
                ('fasteners_distance', models.IntegerField()),
                ('diameter', models.FloatField()),
                ('producer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Producer')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('modification', models.CharField(max_length=100)),
                ('type_size', models.CharField(max_length=100)),
                ('disc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Disc')),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tire')),
            ],
        ),
    ]
