# Generated by Django 3.0.5 on 2020-05-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='seoson',
            field=models.CharField(choices=[('Summer', 'Летние'), ('Winter', 'Зимние')], default='L', max_length=6),
        ),
    ]
