# Generated by Django 3.0.4 on 2020-05-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200520_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='tire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
