# Generated by Django 3.0.5 on 2020-05-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200508_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='seoson',
            field=models.CharField(choices=[('Летние', 'Summer'), ('Зимние', 'Winter')], default='L', max_length=6),
        ),
    ]
