# Generated by Django 3.0.5 on 2020-05-12 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200510_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tire_producers', to='api.Producer'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='seoson',
            field=models.CharField(choices=[('Летние', 'Summer'), ('Зимние', 'Winter'), ('Всесезонные', 'Mixed')], default='L', max_length=11),
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=150)),
                ('model', models.CharField(max_length=150)),
                ('year', models.IntegerField()),
                ('modification', models.CharField(max_length=100)),
                ('type_size', models.CharField(max_length=100)),
                ('tire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_tires', to='api.Tire')),
            ],
        ),
    ]
