# Generated by Django 3.0.5 on 2020-05-16 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200512_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='tire',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Tire'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='producer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Producer'),
        ),
        migrations.AlterField(
            model_name='tire',
            name='seoson',
            field=models.CharField(choices=[('Летние', 'Summer'), ('Зимние', 'Winter'), ('Всесезонные', 'Mixed')], default='Summer', max_length=11),
        ),
    ]
