# Generated by Django 3.0.5 on 2020-05-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disc',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tire',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
