# Generated by Django 3.0.4 on 2020-05-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tire_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tire',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
